name = "WindyGridWorld"
uuid = "a6bea1d8-6c12-4fb3-b32c-726875c8b04c"
authors = ["Unknown "]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Reinforce = "0376cc21-f8a9-5fcf-8891-fde1415a4fd3"
